name: build-image

on:
  push:
    branches:
    - develop
    paths:
    - 'tox.ini'
    - 'tests/make_tox_container.sh'
    - 'tests/make_pdns_container.sh'
    - '.github/workflows/build-image.yml'
  pull_request:
    branches:
    - develop
    paths:
    - 'tox.ini'
    - 'tests/make_tox_container.sh'
    - 'tests/make_pdns_container.sh'
    - '.github/workflows/build-image.yml'
  schedule:
    - cron: "15 4 * * 6"

jobs:
  build-tox:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build tox image
      run: tests/make_tox_container.sh
    - name: display image name
      run: echo ${new_image}
    - name: login to quay.io
      if: github.event_name != 'pull_request'
      run: buildah login -u="kpfleming" -p="${{ secrets.QUAY_TOKEN }}" quay.io
    - name: publish image to quay.io
      if: github.event_name != 'pull_request'
      run: buildah push ${new_image}
  build-pdns:
    runs-on: ubuntu-latest
    needs: build-tox
    strategy:
      matrix:
        pdns: [4.2, 4.3, master]
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build pdns image
      run: tests/make_pdns_container.sh ${{ matrix.pdns }}
    - name: display image name
      run: echo ${new_image}
    - name: login to quay.io
      if: github.event_name != 'pull_request'
      run: buildah login -u="kpfleming" -p="${{ secrets.QUAY_TOKEN }}" quay.io
    - name: publish image to quay.io
      if: github.event_name != 'pull_request'
      run: buildah push ${new_image}
  trigger-ci:
    runs-on: ubuntu-latest
    needs: build-pdns
    steps:
    - name: trigger CI
      if: github.event_name != 'pull_request'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TRIGGER_TOKEN }}
        event-type: trigger-ci
